### PR TITLE
build.md: Update and improve readability/usability

### PR DESCRIPTION
**Pull request by floand**
The [Building NeoMutt](https://www.neomutt.org/dev/build) page could be more interactive and easier to read.
Therefore I will propose my work on this.

Main changes:
- reformat to avoid concatenated lines in resulting web page
- protect long command option dashes to avoid ‘--’ to ‘—’ conversion
- fixing several case insensitivity of proper names and acronyms
- combine multiple configure subsections into one table
- convert different text passages and URIs into clickable links
- add additionally links for further reading and information
- add hopefully correct annotations <sup>[[1]](#fn1)</sup> to workflow examples
- add status WIP due to upcoming autosetup build system transition

<a name="fn1"><sup>[1]</sup></a> because I'm not a developer

Regards

### CODE REVIEW

**Comment by flatcap** [comment]
Thanks for doing that @floand, it's been on my todo list forever.

I have a few suggestions:
- Drop the 'mutt+patch' section
  It's been six months since we supported it
- `--enable-hcache` option doesn't exist any more
  Using any of the `--with-DB` options is enough
- Change the four `--without-DB` options to be `--with-DB`
  The header cache backends are off by default.
  The need for `--without-X` dates back to when we could only have one backend

**Comment by floand** [comment]
Thank you @flatcap for your advice. Reading your replies is always a pleasure due to the explanation that mostly follows your statements. Keep up this fine style it helps a lot those who are eager to learn to understanding things.

I’ve implemented your suggestions and would like to proceed consistently but need once more some hints:

1. I’ve been using links to sections of other internal pages and would like to respect the fixed site banner offset (as discussed in issue #25). Should this be done and if yes, within this PR or by a new one?

2. Also I linked two RFCs (for GSSAPI and SASL) which aren’t in the ‘**_rfc**’ directory yet. Firstly, is that OK or too technical (and useless therefore)? If it’s fine, I assume the content of ‘**_rfc**’ directory is automatically generated but secondly, I have no clue what must be done to get those RFCs into that folder so I could refer/link to them.

3. [**Off Topic**]: Are there any policies how to edit Markdown files related to file encoding, special characters and readability? For instance, what is the prefered way to write, e.g. an em-dash, ellipsis or non-printable characters? For the latter I assume HTML entities like `&nbsp;` or `&#x202F;` are prefered to see it is there and different from a regular space, whereas for the former, writing those characters directly as UTF-8 char will save some space and increase readability instead of using literal `---` or `...`.

What do you think?

**Comment by flatcap** [comment]
> Keep up this fine style

Will do :-)

> links to sections of other internal pages and would like to respect the fixed site banner offset.
> Should this be done and if yes, within this PR or by a new one?

Given the 'open' description of this PR, you can just add more commits.

> Also I linked two RFCs ... is that OK or too technical

The audience are builders, but not necessarily developers.
I think linking to Wikipedia might be a better idea.

> Also I linked two RFCs (for GSSAPI and SASL) which aren’t in the ‘_rfc’ directory yet

I copied all the RFCs that were mentioned in the code and docs.
The list is nowhere near complete.

> I have no clue what must be done to get those RFCs into that folder

It's very crude.  I cut'n'pasted them from the IETF and have a script to give them line numbers.
Give me a list and I'll add more

> Are there any policies how to edit Markdown files related to file encoding, special characters and readability?

No.  I hadn't given it any thought.

The website is very patchy.  It grows whenever I have time to write something, but I haven't had time to make things consistent.

If you'd like to make a list of your suggestions, we can put it somewhere prominent and encourage people to follow it.

Thanks.

**Comment by floand** [comment]
> I think linking to Wikipedia might be a better idea.

Done. That was my first thought, especially they refer to these technical docs also — but then I
stumbled over the “RFCs” pages on the web site... :-)

> Give me a list and I'll add more

For now it’s solved and I don’t want distracting you from more important things.

> ...but I haven't had time to make things consistent.

I’d like to help but fear to become a burden if I don’t know exactly what “consistent” means.

Also I noticed some other things like broken links, usage of `http` scheme instead of a possible
`https` or ideas came up to combine “Branch Names” and “List of Repos” pages, etc.

But as I said, don’t want to distract somebody from prioritised things by offering multiple tiny
topic related PRs or even one huge crossover topic PR. Therefore, hints are welcome.

> If you'd like to make a list of your suggestions, we can put it somewhere prominent and
encourage people to follow it.

I’m quiet new to the whole Markdown stuff with all its different flavours. I use it, sure, but have
not really an overview about the magic behind the scene (72 hours back, I neither heard about
things like _kramdown_ nor was using _Jekyll_). So currently the list of suggestions would be very
short but I’ll keep it on my radar and maybe, the list grows over the time.

Thanks for (the) input.

**Comment by flatcap** [comment]
> fear to become a burden

That's not going to happen.
Even if **I** don't have time to help, there are others.
@toogley has done a lot of great work on the site.  He's knowledgeable.

Also, there are lots of us in #neomutt on irc.freenode.net
(it's fairly sociable in there :-)

> if I don’t know exactly what “consistent” means.

Consistent: the same throughout the whole website.
If we decide on a few style rules, they should be used the same way everywhere.

The website has been thrown together in a hurry.
There's lots of useful information, but it lacks structure (and linking).
Plus, it's very _flatcap-centric_.  A lot of it was written by me when there weren't really any other developers.
It could do with an editor changing the "I..." to "We..." or "The Team..."

> Also I noticed some other things like broken links, usage of http scheme instead of a possible
> https or ideas came up to combine “Branch Names” and “List of Repos” pages, etc.

Great.  Please fix them.

> offering multiple tiny topic related PRs ...

If you're just fixing things, there's no need for PRs, you can commit directly.
Changes committed to master will appear on the website (usually) within minutes.
If you have some bigger ideas, then create an Issue labelled "Discussion".

> not really an overview about the magic behind the scene

The website is a little complicated.  There are both html and markdown pages.
Some of the markdown pages are in "collections" (see [_config.yml](https://github.com/neomutt/neomutt.github.io/blob/master/_config.yml)).
The markdown pages are rendered into html using the "liquid" language (part of Jekyll).
See: [_layouts](https://github.com/neomutt/neomutt.github.io/tree/master/_layouts) and [_includes](https://github.com/neomutt/neomutt.github.io/tree/master/_includes) dirs.

Mostly, I've been playing around with features of Jekyll :-)

**Pull request merged**
