### PR TITLE
Upgrade bootstrap and polish the header

### PR DESCRIPTION
**Pull request by WhyNotHugo**
The previous header had issues at specific screen sizes. On such issue
is that when the window was somewhat narrow (half the screen width at
21:9), the header would overlap with the top of the regular page
content.

Before setting out to patch details on the header, I though it best to
upgrade to a newer bootstrap version. I then fixed the original issue,
and also improved the vertical alignment of the elements in the header
(which is easier with a newer bootstrap). I also shrunk the Agola search
bar a tiny bit, so that the header does not overflow as easily on
not-too-wide screens.

I'm still not convinced about the GitHub image on the upper right
corner. On small screens, after expanding the header, this image covers
up the menu button, so it's impossible to click it or to collapse the
menu again.

### CODE REVIEW

**Review by flatcap — CHANGES_REQUESTED** [review]
Thanks! :heart: This is great!

Years ago, when I set up the website, I just cut'n'paste some sample code, and made it green :-)
I've hacked it up a bit since, but not with any know-how.

> upgrade to a newer bootstrap version

Comparing the two sites, things look a bit different, to be expected,
however the change now means that all the links are underlined.
I'd prefer that they weren't (unless best practices say they should be).

> GitHub image on the upper right

I like that, it's cute and I'm happy to advertise them (for now ;-)
Is there anything we can do to hide it?
I understand that some `<div>`s are hidden at screen sizes.

**Comment by flatcap** [comment]
> all the links are underlined.

Can you fix this please.
Then I can merge your improvements.

**Comment by WhyNotHugo** [comment]
> however the change now means that all the links are underlined.

This was unintentional.

> I'd prefer that they weren't (unless best practices say they should be).

It kinda is, but I don't think it's a hard rule.

I've removed them, but left them on mouse hover.

**Comment by flatcap** [comment]
> This was unintentional

no worries

> I've removed them, but left them on mouse hover.

perfect

**Review by flatcap — APPROVED** [review]
It looks perfect!
Thanks again

**Pull request merged**
